package ViewsBase;

public enum PopUpType {
    COMPANYINFONAV,
    ADDJOBORDERSUBVIEW,
    ADDINTERVIEWSUBVIEW,
    ADDEVALUATIONSUBVIEW,
    ADDJOBCONTRACTSUBVIEW,
    ADDNEWSKILLSUBVIEW,
    ADDSKILLCATEGORYSUBVIEW
}
