package ViewsBase;

public enum TabType1 {
    ADMINHOMETAB,
    APPLICANTHOMETAB,
    COMPANYHOMETAB,
    LISTVIEWTAB,
    SETTINGSTAB,
    MYACCOUNTTAB,
    STATISTICSTAB,
    HELPTAB,
    JOBAPPLICATIONTAB,
    SEARCHTAB

}
