package ViewsBase;

public enum ViewType {
    SYSTEMLOGINVIEW,
    ADMINHOMEVIEW,
    APPLICANTHOMEVIEW,
    APPLICANTPERSONALINFORMATIONREGISTRATIONVIEW,
    SYSTEMUSERLOGININFORMATIONVIEW,
    COMPANYHOMEVIEW,
    COMPANYINFORMATIONREGISTRATIONVIEW,
    ADDNEWINTERVIEWSCHEDULE,
    APPLICANTINFOUPDATEVIEW,
    COMPANYREGISTRATIONINTRODUCTIONVIEW,
    FORGETPASSWORDVIEW,
    LOADERVIEW,
    APPLICANTSKILLINFORMATIONVIEW
}
