package DomainObjects;

public enum CompanyType {

    PRIVATE,
    PRIVATELIMITEDCOMPANY,
    SHARECOMPANY,
    COMMERCIALREPRESENTATIVE,
    PUBLICENTERPRISE,
    PARETNERSHIP,
    TRADESECTORALASSOCIATION,
    NONPUBLICENTERPRISE,
    NONGOVERNMENTALORGANIZATION,
    BRANCHOFAFOREIGNCHAMBEROFCOMMERCE,
    HOLDINGCOMPANY,
    FRANCHISING,
    BORDERTRADE,
    INTERNATIONALBIDWINNERSFOREIGNCOMPANIES,
    GOVERNMENTALORGANIZATION

}
