package Views;

public enum TabType {

    ADMINHOMETAB,
    APPLICANTHOMETAB,
    COMPANYHOMETAB,
    APPLICANTSTAB,
    JOBSTAB,
    COMPANIESTAB,
    INTERVIEWSTAB,
    EVALUATIONSTAB,
    SETTINGSTAB,
    MYACCOUNTTAB,
    STATISTICSTAB,
    HELPTAB,
    JOBAPPLICATIONTAB

}
